### ISSUE TITLE
test .net core compatibility

### ISSUE THREAD

**Issue by LxLeChat** [lazywinadmin/AdsiPS#83] opened 2019-10-01 18:41 UTC
https://docs.microsoft.com/en-us/dotnet/api/?view=netcore-3.0&term=direct

GO! :)

**Comment by lazywinadmin** [comment] 2019-10-03 22:51
Thanks @LxLeChat. Duplicate of another issue. WIll close this one and update the older one
#37 duplicate

**Closed by lazywinadmin** 2019-10-03 22:51 UTC
